version: "3.4"
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  main:
    image: coredns/coredns:${COREDNS_TAG}
    network_mode: host
    tty: true
#    ports:
#      - 53:53/udp
    logging: *default-logging
    restart: always
    volumes:
      - ./config:/config
    command: '-conf /config/Corefile'
